# Generated by Django 2.2.13 on 2021-03-23 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
