# Generated by Django 2.2.13 on 2021-03-23 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_categories_updateduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='updateduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_make_category_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
