# Generated by Django 2.2.13 on 2021-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210425_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barimg',
            field=models.ImageField(blank=True, null=True, upload_to='barcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='barurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
