# Generated by Django 2.2.13 on 2021-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='probarcode',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qremain',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='qsell',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='originprice',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20, verbose_name='Origin Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
