# Generated by Django 2.2.13 on 2021-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210501_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
