# Generated by Django 2.2.13 on 2021-06-05 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210605_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
